name: Automated Tests
on: pull_request
jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:16.11-alpine3.23"
        env:
          POSTGRES_USER: local_user
          POSTGRES_PASSWORD: local
          POSTGRES_DB: local_db
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"
      - run: npm ci
      - run: npm test
